# Released under MIT License

# Copyright (c) 2023 Brandon J. Navarro

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Fix WSL network connectivity

# After Workstation Reboot (Only applicaple to my Dev Machine with Hyper-V and VMware Workstation Pro Installed and multiple vswitches)
# Weird Bug where my Physical NIC cannot be assaigned to a Hyper-V vswitch and pull an IP and have network connectivity.
# Weird Work around NAT Host IP with a VMware Virtual Ethernet Adapter and Share "Internet Connection" under Physical NIC settings with an "Internal Only" Hyper-V Switch and connect 
# WSL vswitch to External 'VMware Virtual Ethernet Adapter' This enables VMware Workstation, Hyper-V and WSL to have network Connectivity.
# This only became a problem after upgrading to Windows 11

# On Host, Open Hyper-V Virtual Switch Manager and Change WSL Switch Connection Type to External 'VMware Virtual Ethernet Adapter for VNet8'

# In WSL Renew DHCP IP Lease
sudo dhclient -r
sudo dhclient


# https://learn.microsoft.com/en-us/windows/wsl/troubleshooting#wsl-has-no-network-connectivity-once-connected-to-a-vpn
# WSL has no network connectivity once connected to a VPN
# If after connecting to a VPN on Windows, bash loses network connectivity, try this workaround from within bash. This workaround will allow you to manually override the DNS resolution through /etc/resolv.conf.

# Make a copy of the existing resolv.conf 
sudo cp /etc/resolv.conf /etc/resolv.conf.bak

# Unlink the current resolv.conf and overwrite it
sudo unlink /etc/resolv.conf
sudo mv /etc/resolv.conf.bak /etc/resolv.conf

# Edit /etc/wsl.conf
sudo nano /etc/wsl.conf
# Add this to the file
[network]
generateResolvConf=false

# Edit /etc/resolv.conf 
sudo nano /etc/resolv.conf 
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
#nameserver 172.26.96.1
nameserver # Ip of VPN DNS

# Once you have disconnected the VPN, you will have to revert the changes to /etc/resolv.conf. To do this, do:
cd /etc
sudo mv resolv.conf resolv.conf.bak
sudo ln -s ../run/resolvconf/resolv.conf resolv.conf
