# Released under MIT License

# Copyright (c) 2023 Brandon J. Navarro

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

services:
    web:
        image: cbcrowe/pihole-unbound:2022.08.2
        build: .
        volumes:
            - ./portainer/Files/AppData/Config/PiHole-Unbound/DNS:/etc/dnsmasq.d
            - ./portainer/Files/AppData/Config/PiHole-Unbound:/etc/pihole
        ports:
            - "4443:443/tcp"
            - "53:53/tcp"
            - "53:53/udp"
            - "1010:80/tcp"
        environment:
            - DNS1=127.0.0.1#5335
            - DNS2=127.0.0.1#5335
            - DNSMASQ_USER=pihole
            - DNSSEC=true
            - FTL_CMD=no-daemon
            - FTLCONF_LOCAL_IPV4=0.0.0.0
            - IPv6=True
            - PATH=/opt/pihole:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - PHP_ENV_CONFIG=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf
            - PHP_ERROR_LOG=/var/log/lighttpd/error-pihole.log
            - phpver=php
            - PIHOLE_DOCKER_TAG=2022.08.2
            - PIHOLE_INSTALL=/etc/.pihole/automated install/basic-install.sh
            - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
            - S6_KEEP_ENV=1
            - S6_LOGGING=0
            - S6_OVERLAY_VERSION=v3.1.1.2
            - ServerIP=192.168.0.217
            - TZ=America\New_York
            - WEBPASSWORD=[PASSWORD]
        labels:
            - org.opencontainers.image.created=2022-08-25T23:42:00.098Z
            - org.opencontainers.image.description=Pi-hole in a docker container
            - org.opencontainers.image.licenses
            - org.opencontainers.image.revision=9039a73272e91d811ccda3316d5c5ddb751b7e91
            - org.opencontainers.image.source=https://github.com/pi-hole/docker-pi-hole
            - org.opencontainers.image.title=docker-pi-hole
            - org.opencontainers.image.url=https://github.com/pi-hole/docker-pi-hole
            - org.opencontainers.image.version=2022.08.2
        entrypoint:	
            - /bin/bash -c ./s6-init
        networks:
            - bridge
